### ISSUE TITLE
Tekenen op bestaande bouwlaag geeft Python error

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#182]
Zodra collega's tekenen op bestaande bouwlagen verschijnt er zo nu en dan een foutmelding. Niet altijd, soms bij bestaande bouwlagen en soms bij vrij recent getekende lagen. 

Er is een fout opgetreden bij het uitvoeren van Python code: 
```
IndexError: list index out of range 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\oiv\tools\mapTool.py", line 66, in canvasMoveEvent
    self.snapPt = self.snap_to_point(event.pos(), layerPt)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\oiv\tools\mapTool.py", line 134, in snap_to_point
    polygon = igeometry.asMultiPolygon()[0][0]
IndexError: list index out of range

```
Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.16.5-Hannover Hannover, 58ba7c1ed6

**Comment by ghost** [comment]
Is gebruikersfout. Iom Joost lager geprioriteerd, wordt mogelijk opgepakt maar niet in eerste instantie door ons.
