### ISSUE TITLE
Werkvoorraad

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/OIV_project#218]
Mutatie die in bouwlaag zijn gedaan komen zowel in terrein als in object terug.

Bij het accepteren van lijn mutatie in terrein komt de volgende melding

2022-02-03T09:15:17     WARNING    Traceback (most recent call last):
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\oiv_werkvoorraad.py", line 164, in execute_selected_rows
              WDH.execute_queries(executableFeatures, self.bouwlaagOfObject, True)
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\db_helper.py", line 67, in execute_queries
              result = insert_feature(feat, cursor, conn, layerName, bouwlaagOfObject)
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\db_helper.py", line 149, in insert_feature
              identifier = CH.get_identifier_by_tablename_ob(tableName)
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\helpers\configdb_helper.py", line 73, in get_identifier_by_tablename_ob
              return read_settings(query, False)[0]
             TypeError: 'NoneType' object is not subscriptable
             
Bij het accepteren van de lijn mutatie bij gebouw komt de volgende melding.

2022-02-03T09:13:19     WARNING    Traceback (most recent call last):
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\oiv_werkvoorraad.py", line 164, in execute_selected_rows
              WDH.execute_queries(executableFeatures, self.bouwlaagOfObject, True)
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\db_helper.py", line 67, in execute_queries
              result = insert_feature(feat, cursor, conn, layerName, bouwlaagOfObject)
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\db_helper.py", line 171, in insert_feature
              cursor.execute(query)
              File "C:\PROGRA~1\QGIS 3.22.2\apps\Python39\lib\site-packages\psycopg2\extras.py", line 251, in execute
              return super(RealDictCursor, self).execute(query, vars)
             psycopg2.errors.UndefinedColumn: column t.symbol_name does not exist
             LINE 1: ...ECT naam FROM objecten.veiligh_bouwk_type t WHERE t.symbol_n...

Het betreft hier de zelfde mutatie

Punt mutatie in bouwlaag krijg ik bij accepteren in terrein ook bovenstaande foutmelding.
In gebouw wordt de mutatie wel verwerkt. (geen fout melding)

De functie delete wordt wel geaccepteerd van een lijn mutatie in bouwlaag in werkvoorraad terrein.

**Comment by Oostjoost** [comment]
ik heb een aanpassing gedaan aan een deel van de plugin, waar de zaken worden verwerkt. Echter krijg ik deze melding niet gereproduceerd?
Kun je de reproductie stappen aangeven?

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/commit/0a524d9d0932ed324473ffb40e941de24cb08995
en commit https://github.com/OIV-NL-QGIS/QGIS_project/commit/5ab5982ac3c149c9215cb949af37a763409e1eb0

resolves #218

**Comment by Oostjoost** [comment]
2e melding is verholpen.... 1e kan ik niet thuisbrengen

**Comment by Joachim-Tempelaars** [comment]
1e kan ik niet reproduceren.
Mogelijk veroorzaakt door het niet goed tekenen.
Bij volgende versie test ik dit verder.
