### ISSUE TITLE
Werkvoorraad_vlak gebouw

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/OIV_project#220]
2022-02-03T12:51:02     WARNING    Traceback (most recent call last):
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\oiv_werkvoorraad.py", line 164, in execute_selected_rows
              WDH.execute_queries(executableFeatures, self.bouwlaagOfObject, True)
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\db_helper.py", line 67, in execute_queries
              result = insert_feature(feat, cursor, conn, layerName, bouwlaagOfObject)
              File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\db_helper.py", line 171, in insert_feature
              cursor.execute(query)
              File "C:\PROGRA~1\QGIS 3.22.2\apps\Python39\lib\site-packages\psycopg2\extras.py", line 251, in execute
              return super(RealDictCursor, self).execute(query, vars)
             psycopg2.errors.UndefinedColumn: column t.symbol_name does not exist
             LINE 1: ..., (SELECT t.id FROM objecten.ruimten_type t WHERE t.symbol_n...
              ^

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/commit/0a524d9d0932ed324473ffb40e941de24cb08995
en commit https://github.com/OIV-NL-QGIS/QGIS_project/commit/5ab5982ac3c149c9215cb949af37a763409e1eb0

resolves https://github.com/OIV-NL-QGIS/QGIS_project/issues/220
