### ISSUE TITLE
Foutmelding bij werkvoorraad update accepteer opslaan

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/OIV_project#229]
Er is een fout opgetreden bij het uitvoeren van Python code: 

TypeError: 'NoneType' object is not subscriptable 
Traceback (most recent call last):
  File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\oiv_werkvoorraad.py", line 164, in execute_selected_rows
    WDH.execute_queries(executableFeatures, self.bouwlaagOfObject, True)
  File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\db_helper.py", line 69, in execute_queries
    result = update_feature(feat, cursor, conn, layerName, bouwlaagOfObject)
  File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\werkvoorraad\db_helper.py", line 118, in update_feature
    identifier = CH.get_identifier_by_tablename_ob(tableName)
  File "C:\Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\oiv\helpers\configdb_helper.py", line 73, in get_identifier_by_tablename_ob
    return read_settings(query, False)[0]
TypeError: 'NoneType' object is not subscriptable

Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python pad:
C:/PROGRA~1/QGIS 3.22.3/apps/qgis/./python
C:/Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python
C:/Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins
C:/PROGRA~1/QGIS 3.22.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS 3.22.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.22.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS 3.22.3\apps\Python39
C:\PROGRA~1\QGIS 3.22.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.22.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS 3.22.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.22.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.22.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/vrbzo-user/AppData/Roaming/QGIS/QGIS3\profiles\test/python
C:/ProgramData/OIV-3.3.9

**Comment by Joachim-Tempelaars** [comment]
Opgelost
Oude oiv map verwijderd in  C:\Users\naamgebruiker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
