### ISSUE TITLE
Migratiescript werkvoorraad

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#331]
De module werkvoorraad werkt momenteel bij ons niet goed. We gebruiken release https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.2. 
Begreep net in het wekelijks overleg dat er een migratiescript is dat gerund moet worden voordat de werkvoorraad werkt (we gebruiken dit nu om zaken te verwijderen die tekenaars buiten de plugin om verwijderen). Dit migratiescript zou nog niet op GitHub staan. Graag laten weten wat we moeten draaien om met de werkvoorraad aan de slag te gaan.

**Comment by ghost** [comment]
We gebruiken QGIS 3.22. Als je klikt op werkvoorraad zie je:


```
AttributeError: 'NoneType' object has no attribute 'getFeatures' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python/plugins\oiv\bag_pand\oiv_pandgegevens.py", line 215, in run_werkvoorraad
    werkvoorraadWidget.initUI()
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python/plugins\oiv\werkvoorraad\oiv_werkvoorraad.py", line 54, in initUI
    self.getData()
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python/plugins\oiv\werkvoorraad\oiv_werkvoorraad.py", line 68, in getData
    it = ilayer.getFeatures(request)
AttributeError: 'NoneType' object has no attribute 'getFeatures'

Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.22.13-Białowieża Białowieża, 02ff117c 
Python pad:
•	C:/PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python
•	C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python/plugins
•	C:\PROGRA~1\QGIS32~1.13\bin\python39.zip
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\DLLs
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib
•	C:\PROGRA~1\QGIS32~1.13\bin
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\win32
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\Pythonwin
•	C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/ProgramData/OIV-3.4.2
```


Als je vervolgens klikt op terug:
```
TypeError: disconnect() failed between 'clicked' and all its connections 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python/plugins\oiv\bag_pand\oiv_pandgegevens.py", line 229, in close_object_show_base
    self.helpBtn.clicked.disconnect()
TypeError: disconnect() failed between 'clicked' and all its connections

Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.22.13-Białowieża Białowieża, 02ff117c 
Python pad:
•	C:/PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python
•	C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python/plugins
•	C:\PROGRA~1\QGIS32~1.13\bin\python39.zip
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\DLLs
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib
•	C:\PROGRA~1\QGIS32~1.13\bin
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\win32
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\site-packages\Pythonwin
•	C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/ProgramData/OIV-3.4.2
```

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_mobiel_3.4.2-3.4.3.sql

En er zit nog een kleine foutmelding bij het openen van een formulier. Is er al uitgehaald maar nog niet in de release omdat OIV mobiel nog niet in de release zat.

**Comment by Oostjoost** [comment]
Is verholpen in versie 3.5.01

Zie voor het script:
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.5.00-3.5.01.sql

In de tabel algemeen.applicatie is aan te zetten of mobiel gebruikt moet worden of niet.
